### PR TITLE
Lloyd core fix

### PR DESCRIPTION
**Pull request by lmckenzi**
Updates from Marc to allow publisher to work w/ recent core changes + small change from me so that publisher doesn't bomb when the core spec includes extensions that have a context of other extensions.

### CODE REVIEW

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
you can sort out the conflict - looks like a wrong version used as the base - very old.

**Comment by grahamegrieve** [comment]
Is this still a thing?

**Comment by lmckenzi** [comment]
Super old, so closing.

**Pull request closed without merging**
